export const commonConstant = {

    FETCH_LOGIN_REJECTED     : 'FETCH_LOGIN_REJECTED',
    FETCH_LOGIN_FULFILLED    : 'FETCH_LOGIN_FULFILLED', 

  
    FETCH_REGISTER_REJECTED  : "FETCH_REGISTER_REJECTED",
    FETCH_REGISTER_FULFILLED : "FETCH_REGISTER_FULFILLED",

    FETCH_TOKEN_REJECTED  : "FETCH_TOKEN_REJECTED",
    FETCH_TOKEN_FULFILLED : "FETCH_TOKEN_FULFILLED",
    
    FETCH_BANNER_REJECTED  : "FETCH_BANNER_REJECTED",
    FETCH_BANNER_FULFILLED : "FETCH_BANNER_FULFILLED",
    
    FETCH_TOPSERVICE_REJECTED  : "FETCH_TOPSERVICE_REJECTED",
    FETCH_TOPSERVICE_FULFILLED : "FETCH_TOPSERVICE_FULFILLED",
    

    FETCH_GETPROFILE_REJECTED  : "FETCH_GETPROFILE_REJECTED",
    FETCH_GETPROFILE_FULFILLED : "FETCH_GETPROFILE_FULFILLED",
    
    FETCH_SWITCH_REJECTED  : "FETCH_SWITCH_REJECTED",
    FETCH_SWITCH_FULFILLED : "FETCH_SWITCH_FULFILLED",
    
    FETCH_GET_SELLER_REJECTED  : "FETCH_GET_SELLER_REJECTED",
    FETCH_GET_SELLER_FULFILLED : "FETCH_GET_SELLER_FULFILLED",
    
    FETCH_Earning_REJECTED  : "FETCH_Earning_REJECTED",
    FETCH_Earning_FULFILLED : "FETCH_Earning_FULFILLED",

    FETCH_BankDetails_REJECTED  : "FETCH_BankDetails_REJECTED",
    FETCH_BankDetails_FULFILLED : "FETCH_BankDetails_FULFILLED",
    
    FETCH_RSRVCE_REJECTED  : "FETCH_RSRVCE_REJECTED",
    FETCH_RSRVCE_FULFILLED : "FETCH_RSRVCE_FULFILLED",

    FETCH_CATSRVCE_REJECTED  : "FETCH_CATSRVCE_REJECTED",
    FETCH_CATSRVCE_FULFILLED : "FETCH_CATSRVCE_FULFILLED",
    
    FETCH_CATEGORY_REJECTED  : "FETCH_CATEGORY_REJECTED",
    FETCH_CATEGORY_FULFILLED : "FETCH_CATEGORY_FULFILLED",
    
    FETCH_SRVCE_REJECTED  : "FETCH_SRVCE_REJECTED",
    FETCH_SRVCE_FULFILLED : "FETCH_SRVCE_FULFILLED",
    
    FETCH_GETORDERS_REJECTED   : "FETCH_GETORDERS_REJECTED",
    FETCH_GETORDERS_FULFILLED  : "FETCH_GETORDERS_FULFILLED",
    
    FETCH_SellerOrder_REJECTED   : "FETCH_SellerOrder_REJECTED",
    FETCH_SellerOrder_FULFILLED  : "FETCH_SellerOrder_FULFILLED",
    
    FETCH_GETORDER_REJECTED   : "FETCH_GETORDER_REJECTED",
    FETCH_GETORDER_FULFILLED  : "FETCH_GETORDER_FULFILLED",

    FETCH_Messages_REJECTED   : "FETCH_Messages_REJECTED",
    FETCH_Messages_FULFILLED  : "FETCH_Messages_FULFILLED",
    
    FETCH_GETITEMS_REJECTED  : "FETCH_GETITEMS_REJECTED",
    FETCH_GETITEMS_FULFILLED : "FETCH_GETITEMS_FULFILLED",
    
    FETCH_ADDITEM_REJECTED   : "FETCH_ADDITEM_REJECTED",
    FETCH_ADDITEM_FULFILLED  : "FETCH_ADDITEM_FULFILLED",

    FETCH_UserReviews_REJECTED   : "FETCH_UserReviews_REJECTED",
    FETCH_UserReviews_FULFILLED  : "FETCH_UserReviews_FULFILLED",
    
    FETCH_RunningOrder_REJECTED   : "FETCH_RunningOrder_REJECTED",
    FETCH_RunningOrder_FULFILLED  : "FETCH_RunningOrder_FULFILLED",
    
    FETCH_SELLERSERVICES_REJECTED   : "FETCH_SELLERSERVICES_REJECTED",
    FETCH_SELLERSERVICES_FULFILLED  : "FETCH_SELLERSERVICES_FULFILLED",
    
    FETCH_DELETESERVICE_REJECTED   : "FETCH_DELETESERVICE_REJECTED",
    FETCH_DELETESERVICE_FULFILLED  : "FETCH_DELETESERVICE_FULFILLED",

    FETCH_ADD_SELLER_REJECTED   : "FETCH_ADD_SELLER_REJECTED",
    FETCH_ADD_SELLER_FULFILLED  : "FETCH_ADD_SELLER_FULFILLED",

    FETCH_CHECK_BUTTON_REJECTED   : "FETCH_CHECK_BUTTON_REJECTED",
    FETCH_CHECK_BUTTON_FULFILLED  : "FETCH_CHECK_BUTTON_FULFILLED",
    
    FETCH_WITHDRWAL_REJECTED   : "FETCH_WITHDRWAL_REJECTED",
    FETCH_WITHDRWAL_FULFILLED  : "FETCH_WITHDRWAL_FULFILLED",

    FETCH_SEARCH_REJECTED   : "FETCH_SEARCH_REJECTED",
    FETCH_SEARCH_FULFILLED  : "FETCH_SEARCH_FULFILLED",
    
    FETCH_Notifiations_REJECTED   : "FETCH_Notifiations_REJECTED",
    FETCH_Notifiations_FULFILLED  : "FETCH_Notifiations_FULFILLED",

    FETCH_Change_OrderStatus_REJECTED   : "FETCH_Change_OrderStatus_REJECTED",
    FETCH_Change_OrderStatus_FULFILLED  : "FETCH_Change_OrderStatus_FULFILLED",

    
    FETCH_CreateOrder_REJECTED   : "FETCH_CreateOrder_REJECTED",
    FETCH_CreateOrder_FULFILLED  : "FETCH_CreateOrder_FULFILLED",

    FETCH_PlaceOrder_REJECTED   : "FETCH_PlaceOrder_REJECTED",
    FETCH_PlaceOrder_FULFILLED  : "FETCH_PlaceOrder_FULFILLED",

    
    
    
    
  }